export const defaultUrl = "https://gateway.marvel.com/v1/public";
export const apiKey =
  "ts=1&apikey=91be78972d82106050f505079b35b784&hash=641501e8f4a3c45c6608e0e0d1bffc7d";

export const TYPES = {
  GET_CHARACTERS: "GET_CHARACTERS",
  GET_CHARACTER_ID: "GET_CHARACTER_ID",
  GET_CHARACTER_NAME: "GET_CHARACTER_NAME",
  SET_LOADING: "SET_LOADING",
  GET_COMICS: "GET_COMICS",
  GET_COMIC_ID: "GET_COMIC_ID",
  GET_SERIES: "GET_SERIES",
  GET_SERIE_ID: "GET_SERIE_ID",
  GET_STORIES: "GET_STORIES",
  GET_STORIE_ID: "GET_STORIE_ID",
};
